trino:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: admin
      password: [password]  # required if method is ldap or kerberos
      database: minio
      host: trino-coordinator
      port: 8443
      schema: dvdrental
      threads: 1
      http_scheme: https
      verify: false

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [prod_user]
      password: [prod_password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [prod_schema]
      threads: [1 or more]

  target: dev

iceberg:
  outputs:

    dev:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: admin
      password: [password]  # required if method is ldap or kerberos
      database: iceberg
      host: trino-coordinator
      port: 8443
      schema: dvdrental
      threads: 1
      http_scheme: https
      verify: false

    prod:
      type: trino
      method: none  # optional, one of {none | ldap | kerberos}
      user: [prod_user]
      password: [prod_password]  # required if method is ldap or kerberos
      database: [database name]
      host: [hostname]
      port: [port number]
      schema: [prod_schema]
      threads: [1 or more]

  target: dev
